name: Build VM Disk Image

env:
  PACKER_VERSION: '1.12.0'

on:
  push:
    branches: '*'
    tags: 'v*'
  pull_request:
    branches:
      - master

jobs:
  build:
    name: ${{ matrix.version.name }}, ${{ matrix.architecture.name }}
    runs-on: ubuntu-latest
    strategy:
        matrix:
          version:
            - name: 'r1beta5'
              uname_version: hrev57937

          architecture:
            - name: x86-64
              uname: x86_64
              qemu: x86
              qemu_executable: x86_64

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set permissions to allow using KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | \
            sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Install Dependencies
        run: |
          sudo apt update && \
          sudo apt install -y \
          fdisk \
          dosfstools \
          rsync \
          curl \
          python3 \
          qemu-system-${{ matrix.architecture.qemu }}

      - name: Print QEMU version
        run: '"qemu-system-${{ matrix.architecture.qemu_executable || matrix.architecture.qemu }}" --version'

      - uses: hashicorp/setup-packer@v3
        with:
          version: ${{ env.PACKER_VERSION }}

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     limit-access-to-actor: true

      - name: Build Image
        run: |
          PACKER_LOG=1 ./build.sh \
            '${{ matrix.version.name }}' \
            '${{ matrix.architecture.name }}' \
            -var 'headless=true'

      - name: Start Local HTTP Server
        run: python3 -m http.server 8080 --directory output &

      - name: Create File
        run: echo 'host to guest' > host_to_guest.txt

      - name: Test Image
        uses: cross-platform-actions/action@master
        with:
          operating_system: haiku
          architecture: ${{ matrix.architecture.name }}
          version: '${{ matrix.version.name }}'
          image_url: http://localhost:8080/haiku-${{ matrix.version.name }}-${{ matrix.architecture.name }}.qcow2
          shutdown_vm: false
          shell: bash
          run: |
            set -x
            uname -a
            uname -s
            uname -r
            uname -v
            uname -m
            uname -p
            pwd
            echo $SHELL
            whoami
            hostname
            ls -lah
            env | sort
            [ "`uname -s`" = 'Haiku' ]
            [ "`uname -r`" = '${{ matrix.version.uname_release || matrix.version.name }}' ] || uname -v | grep -q '${{ matrix.version.uname_version }}'
            [ "`uname -m`" = '${{ matrix.architecture.uname || matrix.architecture.name }}' ] || [ "`uname -p`" = '${{ matrix.architecture.uname || matrix.architecture.name }}' ]
            [ "`pwd`" = '/boot/home/home/runner/work/cross-platform-actions-haiku-builder/cross-platform-actions-haiku-builder' ]
            [ "`hostname`" = 'runnervmg1sw1.local' ]
            cat host_to_guest.txt | grep -q 'host to guest'
            echo 'guest to host' > guest_to_host.txt

      - name: Verify File Synchronization
        run: cat guest_to_host.txt | grep -q 'guest to host'

      - name: Extract Version
        id: version
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Extract changelog
        if: startsWith(github.ref, 'refs/tags/v')
        id: extract_changelog
        uses: sean0x42/markdown-extract@v2
        with:
         file: changelog.md
         pattern: '\[${{ steps.version.outputs.version }}\].+'
         no-print-matched-heading: true

      - name: Create Release
        id: create_release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          name: Haiku ${{ steps.version.outputs.VERSION }}
          draft: true
          files: output/*
          body: ${{ steps.extract_changelog.outputs.markdown }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
